### ISSUE TITLE
"HAP Discovery failed, please review config" when using deviceList

### ISSUE THREAD

**Issue by legacycode** [NorthernMan54/homebridge-alexa#408]
Hi,
i am running HomeBridge in a Docker container and followed the readme. I would like to only add the LightBulb's to Amazon Alexa. When using the deviceList with the following configuration i get the following error:

Error:
```
hapNodeJSClient HAP Device discovered Homebridge xyz xyz
hapNodeJSClient Homebridge instance discovered homebridge with 53 accessories
hapNodeJSClient Ready
alexaActions alexaDiscovery
[Alexa] INFO: DeviceList - The following devices are allow => [ 'LightBulb' ]
[Alexa] ERROR: HAP Discovery failed, please review config
```

Config:
```
      {
            "name": "Alexa",
            "username": "user",
            "password": "pass",
            "pin": "pin",
            "routines": false,
            "blind": true,
            "door": false,
            "debug": true,
            "deviceListHandling": "allow",
            "deviceList": [
                "LightBulb"
            ],
            "platform": "Alexa"
        },
```

Docker:
```
version: "2"

services:
  homebridge:
    image: oznu/homebridge
    hostname: homebridge
    restart: always
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
      - HOMEBRIDGE_INSECURE=1
    volumes:
      - /opt/homebridge:/homebridge
```

Without using the deviceList everything seems to work as expected.

Best regards.

legacycode
